# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-03-17 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='testAdd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, null=True, unique=True)),
            ],
            options={
                'db_table': 'testAdd',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Words1',
            fields=[
                ('word', models.TextField(blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'words1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Words2',
            fields=[
                ('word', models.TextField(blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'words2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Words3',
            fields=[
                ('word', models.TextField(blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'words3',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Words4',
            fields=[
                ('word', models.TextField(blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'words4',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Words5',
            fields=[
                ('word', models.TextField(blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'words5',
                'managed': False,
            },
        ),
    ]
