# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-27 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Words1',
            fields=[
                ('word', models.TextField(blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'words1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Words2',
            fields=[
                ('word', models.TextField(blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'words2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Words3',
            fields=[
                ('word', models.TextField(blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'words3',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Words4',
            fields=[
                ('word', models.TextField(blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'words4',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Words5',
            fields=[
                ('word', models.TextField(blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'words5',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='idstudent',
            field=models.TextField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='username',
            field=models.TextField(blank=True, max_length=45, null=True),
        ),
    ]
