# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-27 20:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20160327_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoreinfo',
            name='recordtime',
            field=models.DateTimeField(default=django.utils.timezone.now, primary_key=True, serialize=False),
        ),
    ]
