# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-30 04:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Words1',
            fields=[
                ('word', models.TextField(blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'words1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Words2',
            fields=[
                ('word', models.TextField(blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'words2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Words3',
            fields=[
                ('word', models.TextField(blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'words3',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Words4',
            fields=[
                ('word', models.TextField(blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'words4',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Words5',
            fields=[
                ('word', models.TextField(blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'words5',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ScoreInfo',
            fields=[
                ('recordtime', models.DateTimeField(default=django.utils.timezone.now, primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('idstudent', models.TextField(max_length=20, primary_key=True, serialize=False)),
                ('firstname', models.TextField()),
                ('lastname', models.TextField()),
                ('username', models.TextField(blank=True, max_length=45, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='scoreinfo',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game1.StudentInfo'),
        ),
        migrations.AlterUniqueTogether(
            name='scoreinfo',
            unique_together=set([('recordtime', 'student_id')]),
        ),
    ]
